### ISSUE TITLE
DOI not found

### ISSUE THREAD

**Issue by jose** [devjeetr/DeepTC-Enhancer-Improving-the-Readability-of-Automatically-Generated-Tests#1]
FYI, the DOI in the [README.md](https://github.com/devjeetr/DeepTC-Enhancer-Improving-the-Readability-of-Automatically-Generated-Tests/blob/master/README.md), https://doi.org/10.1145/3324884.34166221, seems to be incorrect.

**Comment by apanichella** [comment]
Hi, this is the DOI we got from the proceeding chairs. However, the proceedings are not online yet. Until then, the DOI won't work.

**Comment by jose** [comment]
Makes sense.  Sorry to bother you.  :-)

**Comment by apanichella** [comment]
No Problem at all :)
